### ISSUE TITLE
GearVR viewer params

### ISSUE THREAD

**Issue by crookookoo** [borismus/webvr-polyfill#153] opened 2016-09-25 20:54 UTC
I've been trying to get the boilerplate-based project to run on the latest GearVR with S7 edge, and ran into issues with eye distance being off by a lot. Using a normal browser outside of gear app it seems like a polyfill issue.

After a brief research, I ended up tweaking the CardboardViewer parameters by trial and error, so that it sorta works. Here is my result:
``` 
label: 'GearVR 2',
fov: 35,
interLensDistance: 0.052,
baselineLensDistance: 0.035,
screenLensDistance: 0.043,
distortionCoefficients: [0.441, 0.156],
inverseCoefficients: [-0.4410035, 0.42756155, -0.4804439, 0.5460139,
      -0.58821183, 0.5733938, -0.48303202, 0.33299083, -0.17573841,
      0.0651772, -0.01488963, 0.001559834]
```
Is there a way to know the actual parameters for GearVR? Would it make sense to add gear as another viewer to polyfill?

**Comment by njam** [comment] 2016-09-26 06:33
Duplicate of https://github.com/borismus/webvr-polyfill/issues/60?

**Comment by borismus** [comment] 2016-09-28 22:51
Yes, thanks.

**Closed by borismus** 2016-09-28 22:51 UTC
