### ISSUE TITLE
iOS Stereo Viewport does not have the correct size

### ISSUE THREAD

**Issue by dmarcos** [borismus/webvr-polyfill#102] opened 2016-05-08 04:47 UTC
When going to VR mode this is what I get on my iPhone 6 (iOS 9.3.1) in Safari

![img_2459](https://cloud.githubusercontent.com/assets/39342/15096066/f64fefae-149c-11e6-81f7-3f134c11033b.PNG)

I don't fully understand what's going on but this fixes the issue:

````javascript
WebVRConfig = {
  BUFFER_SCALE: 1 / window.devicePixelRatio
};
````

**Comment by cvan** [comment] 2016-05-08 04:55
Could be why https://github.com/borismus/webvr-polyfill/blob/a5982b8/examples/basic/index.html#L74 is necessary in the [Basic Example](https://borismus.github.io/webvr-polyfill/examples/basic/)

**Comment by dmarcos** [comment] 2016-05-08 05:43
This bug has been reproduced with the basic example in the master branch (https://github.com/borismus/webvr-polyfill/commit/7986def2632215c243b31536bd079ddeea5215d2) as it is (with https://github.com/borismus/webvr-polyfill/blob/a5982b8/examples/basic/index.html#L74)

**Comment by brianchirls** [comment] 2016-05-08 21:04
So glad you filed this @dmarcos. I've been fighting this one for days. It seems that if I manually change the CSS dimensions of the canvas using Safari dev tools, it fixes it. I have no idea why.

**Comment by capnmidnight** [comment] 2016-05-08 21:19
Hey guys, got a weird question for you. When you detect there is a problem,
can you check to see if your Three.js `renderer.domElement !==
document.getElementByID(renderer.domElement.id)`? When things go wrong,
that test returns true. When everything is working fine, that test returns
false.

I know it looks insane, but I've been encountering an error mode in
Primrose on Firefox that "fixes" when I manually set CSS properties in the
developer console, and this test returning true is all the further I've
gotten on debugging it so far. Just curious to see if something similar is
going on.

**Comment by brianchirls** [comment] 2016-05-09 00:58
@capnmidnight: No, the test returns `false` whether or not the bug is happening.

**Comment by capnmidnight** [comment] 2016-05-09 02:25
Ok, thanks. I've figured out my problem. In my particular case, I need to
wait until `document.readyState === "complete"` before creating the
renderer, because DOM element references acquired before that time won't be
the same objects as the DOM elements in the document after "complete". IDK
if that is useful or relevant, but something good to know.

Thank you,
Sean T. McBeth
CEO, Primrose LLC <http://www.primrosevr.com>
@Sean_McBeth
T:> 717.261.7689 <//717.261.7689>

**Comment by borismus** [comment] 2016-05-09 16:36
Are you using THREE r75? There are known broken things with THREE r76, try with the dev branch.

**Comment by brianchirls** [comment] 2016-05-09 17:17
I'm using r76 of three.js and `VREffect` from the dev branch, to incorporate all that stuff we just fixed over the last week or so.

**Comment by borismus** [comment] 2016-05-09 17:21
And this is on an iPhone 6 (not S, not Plus)?

**Comment by brianchirls** [comment] 2016-05-09 17:23
It's on all the iPhones I've run in the simulator, including the iPhone 6.

**Comment by dmarcos** [comment] 2016-05-09 17:47
I've reproduced on iPhone6 and iPhone6 Plus (I don't have an S)

**Comment by dmarcos** [comment] 2016-05-09 18:21
The problem reproduces as well with three.js / VREffect / VRControls from dev branch (commit https://github.com/mrdoob/three.js/commit/9c8af29961e6098466a3b5931e4b92731835f65d). It does not reproduce though with three.js r75

**Comment by OliwerLarsson** [comment] 2016-05-10 12:05
I can reproduce the problem with three.js r75 and iphone 5s when i start in in portrait and i rotate the device and enter fullscreen and when i start in landscape and i swipe to enter fullscreen.
it does not reproduce if i start in landscape and i dont swipe up

**Comment by OliwerLarsson** [comment] 2016-05-10 13:02
I just did `<meta name="viewport" content="width=device-width, minimum-scale=0.3, maximum-scale=1.0">` doesn't the canvas get set with the actual resolution of your device rather than what the browser pretends it to be?

**Comment by dmarcos** [comment] 2016-05-10 18:27
https://github.com/borismus/webvr-polyfill/commit/a5982b8f2d746592c30038fd4cf48300da10a0dc commit works as expected on my iphone6 Plus. The regression was introduced after that one.

**Comment by brianchirls** [comment] 2016-05-10 19:33
It looks like the problem started in https://github.com/borismus/webvr-polyfill/commit/54a815628b87e5a9b4849fc71a518de481ff70b3

This commit doesn't have a descriptive message and is too big to view in detail because it includes a bunch of unrelated files. @borismus can you give us some insight into what changes you made? or possibly help debug this? Thanks.

**Comment by OliwerLarsson** [comment] 2016-05-11 09:24
It's the setSize function in `VREffect.js` that is setting the canvas size to your phones actual resolution which combined with `minimum-scale=1.0` makes it larger than your phone allows.

If you change this in `VREffect.js`

```
	this.setSize = function ( width, height ) {

		rendererSize = { width: width, height: height };

		if ( isPresenting ) {

			var eyeParamsL = vrHMD.getEyeParameters( 'left' );
			renderer.setPixelRatio( 1 );

			if ( isDeprecatedAPI ) {

				renderer.setSize( eyeParamsL.renderRect.width * 2, eyeParamsL.renderRect.height, false );

			} else {

				renderer.setSize( eyeParamsL.renderWidth * 2, eyeParamsL.renderHeight, false );

			}


		} else {

			renderer.setPixelRatio( rendererPixelRatio );
			renderer.setSize( width, height );

		}

	};
```

to this

```
	this.setSize = function ( width, height ) {

        renderer.setSize( width, height );

	};
```

which is what is part of what was changed in https://github.com/borismus/webvr-polyfill/commit/54a815628b87e5a9b4849fc71a518de481ff70b3

however if you do this you'll get a lower resolution image just like decreasing the buffer size by half

**Comment by brianchirls** [comment] 2016-05-11 16:07
It looks like @toji has a fix for this in #106, though it needs some further review.

**Comment by brianchirls** [comment] 2016-05-19 14:38
This looks fixed to me.

**Comment by borismus** [comment] 2016-05-19 15:44
Agree

**Closed by borismus** 2016-05-19 15:44 UTC
